### PR TITLE
Use OpenSSL for aes*-ctr

### LINKED ISSUE #542: Slow file upload via CTR mode of encryption
### Expected behavior

Uploading via SCP using CTR encryption mode should be comparable to using CBC.

### Actual behavior

CTR encryption mode is ~46x slower than CBC.  For a 79MB file upload via SCP:

*aes128-ctr*
```
real    1m17.345s
user    1m15.700s
sys     0m1.464s
```
*aes128-cbc*
```
real    0m2.538s
user    0m1.688s
sys     0m0.680s
```

### System configuration

- net-ssh version: 2.7.0 (reproducible on 4.1.0)
- Ruby version: 2.2.6 (jemalloc)

### Example App

```ruby
#gem 'net-ssh', '= 2.7.0'
gem 'net-scp', '= 1.1.2'
require 'net/scp'
puts Net::SSH::Version::CURRENT

@host = ENV['HOST']
@user = ENV['USER']
Net::SCP.start(@host, @user, encryption: ENV['ENCRYPTION'] || 'aes128-cbc') do |scp|
  # The file /tmp/testdata was created using
  #   dd if=/dev/random of=/tmp/testdata count=1024000
  scp.upload!('/tmp/testdata', '/tmp/testdata')
end
```

### PR DESCRIPTION
**Pull request by mfazekas**
Closes #542

### CODE REVIEW

**Comment by apachelogger** [comment]
@mfazekas This is pretty much where I got stuck at. In theory that is what openssh's implementation does (cipher.c for the record), but something is awry with the packet length we construct.
Which is also why the integration tests fail on travis.

sshd complaint:
```
Feb 05 14:05:16 ajax sshd[1023]: Connection from 127.0.0.1 port 39790 on 127.0.0.1 port 22
Feb 05 14:05:16 ajax sshd[1023]: debug1: Client protocol version 2.0; client software version Ruby/Net::SSH_5.0.0.beta1 x86_64-linux
Feb 05 14:05:16 ajax sshd[1023]: debug1: no match: Ruby/Net::SSH_5.0.0.beta1 x86_64-linux
Feb 05 14:05:16 ajax sshd[1023]: debug1: Enabling compatibility mode for protocol 2.0
Feb 05 14:05:16 ajax sshd[1023]: debug1: Local version string SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.4
Feb 05 14:05:16 ajax sshd[1023]: debug1: permanently_set_uid: 124/65534 [preauth]
Feb 05 14:05:16 ajax sshd[1023]: debug1: list_hostkey_types: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519 [preauth]
Feb 05 14:05:16 ajax sshd[1023]: debug1: SSH2_MSG_KEXINIT sent [preauth]
Feb 05 14:05:16 ajax sshd[1023]: debug1: SSH2_MSG_KEXINIT received [preauth]
Feb 05 14:05:16 ajax sshd[1023]: debug1: kex: algorithm: diffie-hellman-group14-sha1 [preauth]
Feb 05 14:05:16 ajax sshd[1023]: debug1: kex: host key algorithm: ecdsa-sha2-nistp256 [preauth]
Feb 05 14:05:16 ajax sshd[1023]: debug1: kex: client->server cipher: aes128-ctr MAC: hmac-sha1 compression: none [preauth]
Feb 05 14:05:16 ajax sshd[1023]: debug1: kex: server->client cipher: aes128-ctr MAC: hmac-sha1 compression: none [preauth]
Feb 05 14:05:16 ajax sshd[1023]: debug1: expecting SSH2_MSG_KEXDH_INIT [preauth]
Feb 05 14:05:16 ajax sshd[1023]: debug1: rekey after 4294967296 blocks [preauth]
Feb 05 14:05:16 ajax sshd[1023]: debug1: SSH2_MSG_NEWKEYS sent [preauth]
Feb 05 14:05:16 ajax sshd[1023]: debug1: expecting SSH2_MSG_NEWKEYS [preauth]
Feb 05 14:05:16 ajax sshd[1023]: debug1: rekey after 4294967296 blocks [preauth]
Feb 05 14:05:16 ajax sshd[1023]: debug1: SSH2_MSG_NEWKEYS received [preauth]
Feb 05 14:05:16 ajax sshd[1023]: debug1: KEX done [preauth]
Feb 05 14:05:16 ajax sshd[1023]: Bad packet length 2603040486. [preauth]
```

**Comment by mfazekas** [comment]
> Which is also why the integration tests fail on travis.

There is only one integration test failing - i'm looking into it
https://travis-ci.org/mfazekas/net-ssh/jobs/337534849

Have you tested my version in #570?

**Comment by mfazekas** [comment]
Yep i'm seeing the same  issue...
```
Feb  5 13:20:29 vagrant-ubuntu-trusty-64 sshd[7010]: Bad packet length 333557815. [preauth]
```

**Comment by mfazekas** [comment]
@apachelogger i've fixed the issue in integration tests, it was related with pattern

```
..
cipher.reset
cipher.iv = ...
...
```

it seems that with ctr this to `iv=` do anyhting as that would reset the counter too. This now fixed the integration test, and simple hello world type stuff is working.

**Comment by mfazekas** [comment]
I'm using the following program to benchmark:

```
$:.push('./lib')
require 'net/ssh'
require 'byebug'
require 'benchmark'
puts Net::SSH::Version::CURRENT
ssh = Net::SSH.start("localhost", ENV["USER"], encryption: 'aes128-ctr')

bytes = 0
mbytes = 0

channel = ssh.open_channel do |channel|
  start = Time.now

  channel.on_data do |ch, data|
    bytes += data.length
    newmbytes = bytes / (1024 * 1024)
    if newmbytes != mbytes
      current = Time.now
      puts "Bytes: #{bytes.inspect} bytes in #{current-start} second"
      mbytes = newmbytes
      rate = bytes.to_f/((1024.0*1024.0)*(current-start).to_f)
      if mbytes > 10
        puts "Rate: #{rate} MB/s"
      end
    end
  end

  channel.exec "cat /dev/urandom"
end
channel.wait
ssh.close
```


Results

- Original:  ~1.0MBytes/sec
- Slice optimized: ~1.5MBytes/sec
- OpenSSL: ~11.0 MBytes/sec

**Comment by apachelogger** [comment]
Yes!

I am in love with this change now. I did expect an improvement when moving to ossl ctr but this is insane.

1.5GiB via openssh sftp
`3,71s user 1,05s system 89% cpu 5,318 total`
with this PR and net-sftp (and 64 pending requests, same as openssh)
` 7,75s user 1,09s system 88% cpu 10,037 total`

:+1: from me

**Pull request merged**
