### PR TITLE
Use host_key_sig_type to compare sig_type as sig_type in package migh…

### PR DESCRIPTION
**Pull request by mfazekas**
Closes: #600

### CODE REVIEW

**Comment by mfazekas** [comment]
@russjones  pls review the fix

**Comment by russjones** [comment]
@mfazekas Thanks for the quick turnaround!

I just tested and the fix works for `diffie-hellman-group1-sha1` KEX. However, the same fix will need to be applied for the other KEX algorithms as well:

* `ecdh_sha2_nistp256`
* `ecdh_sha2_nistp384`
* `ecdh_sha2_nistp521`
* `diffie_hellman_group14_sha1`

For example, here is the output when the server prefers `ecdh_sha2_nistp256`:

```
D, [2018-05-29T17:57:56.691116 #28220] DEBUG -- io[e27728]: received packet nr 1 type 31 len 1420
/var/lib/gems/2.3.0/gems/net-ssh-5.0.0.rc1/lib/net/ssh/transport/kex/ecdh_sha2_nistp256.rb:88:in `send_kexinit': host key algorithm mismatch for signature 'ssh-rsa' != 'ssh-rsa-cert-v01@openssh.com' (Net::SSH::Exception)
	from /var/lib/gems/2.3.0/gems/net-ssh-5.0.0.rc1/lib/net/ssh/transport/kex/diffie_hellman_group1_sha1.rb:71:in `exchange_keys'
	from /var/lib/gems/2.3.0/gems/net-ssh-5.0.0.rc1/lib/net/ssh/transport/algorithms.rb:389:in `exchange_keys'
	from /var/lib/gems/2.3.0/gems/net-ssh-5.0.0.rc1/lib/net/ssh/transport/algorithms.rb:211:in `proceed!'
	from /var/lib/gems/2.3.0/gems/net-ssh-5.0.0.rc1/lib/net/ssh/transport/algorithms.rb:150:in `accept_kexinit'
	from /var/lib/gems/2.3.0/gems/net-ssh-5.0.0.rc1/lib/net/ssh/transport/session.rb:210:in `block in poll_message'
	from /var/lib/gems/2.3.0/gems/net-ssh-5.0.0.rc1/lib/net/ssh/transport/session.rb:190:in `loop'
	from /var/lib/gems/2.3.0/gems/net-ssh-5.0.0.rc1/lib/net/ssh/transport/session.rb:190:in `poll_message'
	from /var/lib/gems/2.3.0/gems/net-ssh-5.0.0.rc1/lib/net/ssh/transport/session.rb:225:in `block in wait'
	from /var/lib/gems/2.3.0/gems/net-ssh-5.0.0.rc1/lib/net/ssh/transport/session.rb:223:in `loop'
	from /var/lib/gems/2.3.0/gems/net-ssh-5.0.0.rc1/lib/net/ssh/transport/session.rb:223:in `wait'
	from /var/lib/gems/2.3.0/gems/net-ssh-5.0.0.rc1/lib/net/ssh/transport/session.rb:90:in `initialize'
	from /var/lib/gems/2.3.0/gems/net-ssh-5.0.0.rc1/lib/net/ssh.rb:242:in `new'
	from /var/lib/gems/2.3.0/gems/net-ssh-5.0.0.rc1/lib/net/ssh.rb:242:in `start'
	from ssh.rb:8:in `<main>'
```

**Comment by mfazekas** [comment]
@russjones thanks for catching that. 
I've fixed in EcdhSHA2NistP256 too, which inherits from DiffieHellmanGroup1SHA1 too but did override this part. These 2 codepaths should cover every kex now.

**Comment by russjones** [comment]
@mfazekas Thanks, just re-tested and everything works.

**Pull request merged**
