### PR TITLE
Add support for IdentityAgent in ssh_config

### PR DESCRIPTION
**Pull request by frenkel**
This commit adds support for configuring the IdentityAgent through an SSH config file.

### CODE REVIEW

**Comment by mfazekas** [comment]
@frenkel  thanks for the PR!

**Comment by vrinek** [comment]
@frenkel @mfazekas I think this PR may have missed one point: `Net::SSH::VALID_OPTIONS`.

I get an `ArgumentError: invalid option(s): identity_agent` exception in my local setup when I have an `IdentityAgent` option in my `~/.ssh/config`.

Would you say this is relevant or should I file it as a separate issue?

**Comment by frenkel** [comment]
I'm not sure, I don't have this error while I use it on a number of computers. Is everything up to date?

**Comment by fwininger** [comment]
@vrinek can you give us your ruby version and the version of net/ssh you use ?

and if you have the complete stack error, this would be awesome.

**Comment by vrinek** [comment]
I'm using `net-ssh` via `capistrano` which gives me `ArgumentError: invalid option(s): identity_agent` for each remote server it's trying to SSH to.

Versions:
Ruby: 2.4.7
Net/SSH: 5.2.0

**Pull request merged**
