### PR TITLE
Add Curve25519Sha256

### PR DESCRIPTION
**Pull request by fwininger**
Implementing the "curve25519-sha256@libssh.org" key-exchange algorithm. 

Defined in https://tools.ietf.org/html/draft-ietf-curdle-ssh-curves-06

### CODE REVIEW

**Comment by mfazekas** [comment]
@fwininger thanks, looks great!!

Not really sure about the `x25519` dependency, with ed25516, we only use that if the user installed it, we might want to consider the same approach

See reasoning from ed25516 at:
https://github.com/net-ssh/net-ssh/issues/476#issue-197976226

And an integration test would be amazing!

**Comment by fwininger** [comment]
I will do the correction quickly ! and after that I work on the implementation of new ciphers (aes-gcm and chacha20-poly1305).

Please can you merge my PR for coding style ? because I need to do some refactoring for the new ciphers.

**Comment by fwininger** [comment]
Hello @mfazekas, I have rebase this PR and change the behaviour to load the code only when the gem x25516 is installed.

I have found no integration test example about kex.

To do advance test on my side I use docker with a debug compilation of openssh : https://github.com/fwininger/docker_ssh_debug

**Comment by mfazekas** [comment]
Thanks! 🥇

**Pull request merged**
