### PR TITLE
Openssl3

### PR DESCRIPTION
**Pull request by fwininger**
duplicate from #857 for test purpose

### CODE REVIEW

**Comment by fwininger** [comment]
This PR close #843

**Review by mfazekas — APPROVED** [review]
👍

**Comment by mfazekas** [comment]
@fwininger will try to cut a new release

**Comment by dbh2** [comment]
> @fwininger will try to cut a new release

Thank you. I upgraded my Oxidized box to Ubuntu 22.04 and it is broken now. I reinstalled everything, downgraded psych, and now I am left at a SSH issue. My understanding is that it is a OpenSSL 3 / Net-SSH issue. Following for the update.

**Comment by proigor** [comment]
> > @fwininger will try to cut a new release
> 
> Thank you. I upgraded my Oxidized box to Ubuntu 22.04 and it is broken now. I reinstalled everything, 

Same for me, still waiting for the new release in order to continue working on 22.04

**Comment by mfazekas** [comment]
I've release 7.0.0 beta1, please test and report back. 
https://rubygems.org/gems/net-ssh/versions/7.0.0.beta1

**Comment by proigor** [comment]
Works for me now, thank you very much!

**Comment by dbh2** [comment]
> Works for me now, thank you very much!

I loaded up the new gem but I still get "pkeys are immutable on OpenSSL 3.0". What other changes did you make other than installing the gem?

**Comment by proigor** [comment]
> > Works for me now, thank you very much!
> 
> I loaded up the new gem but I still get "pkeys are immutable on OpenSSL 3.0". What other changes did you make other than installing the gem?

I changed to:
gem 'net-ssh', '~> 7.0.0.beta1', require: 'net/ssh'
in my Gemfile. And run 'bundle update'.

**Comment by dbh2** [comment]
> > > Works for me now, thank you very much!
> > 
> > 
> > I loaded up the new gem but I still get "pkeys are immutable on OpenSSL 3.0". What other changes did you make other than installing the gem?
> 
> I changed to: gem 'net-ssh', '~> 7.0.0.beta1', require: 'net/ssh' in my Gemfile. And run 'bundle update'.

Will have to do some reading. First and only ruby project I've ever put my hands on. The Gemfile in my /var/lib/gems for oxidized-0.28.0 is basically blank. Thanks for the tip.

**Comment by proigor** [comment]
> Will have to do some reading. First and only ruby project I've ever put my hands on. The Gemfile in my /var/lib/gems for oxidized-0.28.0 is basically blank. Thanks for the tip.

I'm using Rails, so that's a Gemfile inside my project.

**Comment by meidlinga** [comment]
After `gem install net-ssh -v 7.0.0.beta1` I can use `vagrant provision` on Ubuntu 22.04 again. Thank you.

**Comment by edmorley** [comment]
Hi! Is there a timeframe for when v7.0.0 might be released as not a beta? 

We're getting end-user reports of issues using `net-ssh` on Ubuntu 22.04 - and a beta release is much less discoverable for them to think to try before opening a support ticket.

Many thanks :-)

**Comment by fwininger** [comment]
@mfazekas can you release 7.0.0, please ?

**Comment by mfazekas** [comment]
> @mfazekas can you release 7.0.0, please ?

Done

**Pull request merged**
