### PR TITLE
Fix issue #235

### LINKED ISSUE #235: Ruby 2.2 64bit / Pageant / Windows / "bignum too big to convert into `long'"
This issue is exclusive to the **64 bit** build of ruby 2.2.1. The 32bit build runs fine.

The current master (https://github.com/net-ssh/net-ssh/commit/3ed5b1963c1aafbb1ec239b5a0a20cc57ea92194) won't work on ruby 2.2.1-64 / Windows. It fails with this message:

```
SSHKit::Runner::ExecuteError: Exception while executing on host --redacted--: bignum too big to convert into `long'
C:/Tools/Ruby22-x64/lib/ruby/gems/2.2.0/bundler/gems/net-ssh-3ed5b1963c1a/lib/net/ssh/authentication/pageant.rb:191:in `malloc'
C:/Tools/Ruby22-x64/lib/ruby/gems/2.2.0/bundler/gems/net-ssh-3ed5b1963c1a/lib/net/ssh/authentication/pageant.rb:191:in `malloc_ptr'
C:/Tools/Ruby22-x64/lib/ruby/gems/2.2.0/bundler/gems/net-ssh-3ed5b1963c1a/lib/net/ssh/authentication/pageant.rb:255:in `get_token_information'
C:/Tools/Ruby22-x64/lib/ruby/gems/2.2.0/bundler/gems/net-ssh-3ed5b1963c1a/lib/net/ssh/authentication/pageant.rb:228:in `get_current_user'
C:/Tools/Ruby22-x64/lib/ruby/gems/2.2.0/bundler/gems/net-ssh-3ed5b1963c1a/lib/net/ssh/authentication/pageant.rb:204:in `get_security_attributes_for_user'
C:/Tools/Ruby22-x64/lib/ruby/gems/2.2.0/bundler/gems/net-ssh-3ed5b1963c1a/lib/net/ssh/authentication/pageant.rb:347:in `send_query'
C:/Tools/Ruby22-x64/lib/ruby/gems/2.2.0/bundler/gems/net-ssh-3ed5b1963c1a/lib/net/ssh/authentication/pageant.rb:324:in `send'
C:/Tools/Ruby22-x64/lib/ruby/gems/2.2.0/bundler/gems/net-ssh-3ed5b1963c1a/lib/net/ssh/authentication/agent/socket.rb:148:in `send_packet'
```

There has been some work towards 2.2 compatibility in January, so i wonder if this should actually be working or if it was not tested on 64 bit.

The latest release (v2.9.2 at the time of writing) does not work because of the removal of 'dl' in ruby 2.2.

### PR DESCRIPTION
**Pull request by elconas**
Fixes #235

### CODE REVIEW

**Comment by mfazekas** [comment]
Thanks much, looks good. 

Question: could we do integration test for windows side, like we have for unix? 
https://github.com/net-ssh/net-ssh/tree/master/test/integration

Ideally we could run windows tests on appveyor - like https://ci.appveyor.com/project/mfazekas/net-ssh-gp9qw/build/job/hahw7jorjuvluqow it would be a great help.

**Comment by elconas** [comment]
Whats missing to get this integrated ?

**Comment by mfazekas** [comment]
My biggest issue is that i lack the time to install a windows vm to test this out.  Let me ask on the issue thread to get some feedback.

**Comment by ccoenen** [comment]
as requested in #235, I gave this a bit of a test (with the code snippet found in my comment over there).

I can confirm that this worked 10 out of 10 times with ruby 2.2 32bit
I can also gladly confirm that this worked 10 out of 10 times on ruby 2.2 64bit which previously failed! So as far as I can tell, this fixes the issue :tada:

**Pull request merged**
