### PR TITLE
Added support for RSA client authentication with SHA-2

### PR DESCRIPTION
**Pull request by fwininger**
Rebase from https://github.com/net-ssh/net-ssh/pull/811

### CODE REVIEW

**Comment by sae249833** [comment]
+1 on getting this merged ASAP. A new release to include this and https://github.com/net-ssh/net-ssh/pull/771 would also be great.

Thanks!

**Comment by fwininger** [comment]
@mfazekas can you release a new minor version ?

**Comment by svoop** [comment]
Wow, tracking our failing Capistrano deploy (after Gentoo upped to openssh 8.8 yesterday) to this issue took me a while. Bundling from Github fixes the problem, thanks a lot @fwininger ! A (minor) release would still be great thou. /cc @mfazekas

**Comment by trevor-vaughan** [comment]
This fixes issues for me on RHEL 9-based systems since, like Fedora, they also disable `ssh-rsa` out of the box.

**Comment by lnussbaum** [comment]
Hi @mfazekas ,

Do you have plans to release a new version of net-ssh with this fix?
Version 6.3.0beta1 cannot connect to Debian 'testing' machines because of this.

Thanks!

Lucas

**Comment by sarcasticadmin** [comment]
@lnussbaum Im referencing this repo directly as a work around until the release gets cut: https://github.com/socallinuxexpo/scale-network/blob/f4afff18466bc465e872165890c7af171d4c583a/tests/serverspec/Gemfile#L9

Hope that helps

**Comment by Rylon** [comment]
We're having trouble connecting to Ubuntu 22.04 servers which drop support for sha1 and require sha2, which this PR adds support for. If I test by using the current HEAD of this repo, then it works.

Are you planning on cutting a new release of the gem containing the changes from this PR? It would be greatly appreciated, thanks, especially since Ubuntu 22.04 is the new LTS and is out now.

Thanks again :)

**Comment by fwininger** [comment]
I currently work on openssl 3 issue. The master branch is not totaly compliance with ubuntu 22.04.

**Comment by toxaq** [comment]
Just adding this solution for future Googlers to find the solution to the problem that led me here:

https://stackoverflow.com/questions/72068406/capistrano-fail-to-deploy-rails-app-due-to-incompatibility-with-openssl-3-0

Ubuntu 22.04 LTD not accepting Capistrano connections despite identical configs.

**Pull request merged**
