### PR TITLE
Fixing pageant interaction on 64-bit platform 

### PR DESCRIPTION
**Pull request by pleaseking**
fix net-ssh not working with Pageant in 64-bit build. Problem was manually packing arrays into Win32 structures without taking alignment and 32bit/64bit field size discrepancies into account. 

Solved by using Fiddle Struct API - it packs correctly on both 32-bit and 64-bit system. 

Tested in both 32-bit and 64-bit Ruby (2.2.x, 2.1.x)

### CODE REVIEW

**Comment by Antiarchitect** [comment]
Tested on Win x64 with Ruby 2.2.2 x64

**Comment by pleaseking** [comment]
Also tested on Win x64 (Windows Server 2012 R2) with Ruby 2.1.6 x86.

**Comment by mfazekas** [comment]
thanks, much :)

**Comment by thargor** [comment]
Does stilll not work for me with, but now with the following error message on win 8.1 x64 ruby 2.1.5 and net:ssh v2.10.0.beta1.

    SSHKit::Runner::ExecuteError: Exception while executing as root@github.com: to_ptr should return a CPtr object
    DL::DLError: to_ptr should return a CPtr object

Should I open a new bug?

**Comment by pleaseking** [comment]
I think yes, but can you check ruby 2.2.x ?

**Comment by thargor** [comment]
It does connect using the agent with 2.2.1, but then runs into the "bignum too big to convert into `long'"  error from #235

**Pull request merged**
