### PR TITLE
Ruby 2.4 compatibility

### PR DESCRIPTION
**Pull request by camertron**
Ruby 2.4 compat for the 3.x branch of net-ssh.

### CODE REVIEW

**Comment by camertron** [comment]
Are travis builds turned off for this branch or repo?

**Comment by mfazekas** [comment]
@camertron thanks for the PR. What is the usecase? Why do you need 3.*? Can't you just upgrade to 4.*?

This is the travis build:
https://travis-ci.org/net-ssh/net-ssh/builds/236529130?utm_source=github_status&utm_medium=notification

**Comment by camertron** [comment]
Ah thanks @mfazekas. Glad to see the build passed :)

Net-ssh is a dependency of several other gems - specifically chef - that sadly locks the version to < 4.0. I was hoping to not have to upgrade chef (lots of work), but also hoping to silence the deprecation warnings we're currently seeing from our recent upgrade to Ruby 2.4.

This is definitely not critical :)

**Comment by camertron** [comment]
Awesome, thanks @mfazekas! Any chance this could get released at some point? Maybe v3.2.1?

**Pull request merged**
