### PR TITLE
Backport host/sig key format fix from v6 beta

### PR DESCRIPTION
**Pull request by dirkjonker**
This allows net-ssh to be used with ed25519 certificates, for example.

Would be great if this (or with modifications) can be released as a 5.x minor update or 5.2.x patch update for compatibility with net-scp 2.0.

### CODE REVIEW

**Comment by mfazekas** [comment]
@dirkjonker thanks, unfortunately i'm not fan of backporting. I'm trying to get 6.0 released ASAP. We can do a new`net-scp`  release with net-ssh 6.0 compat

**Comment by dirkjonker** [comment]
@mfazekas I can respect that. Anything I can try to help with for 6.0?

**Comment by mfazekas** [comment]
@dirkjonker  i've released 6.0.beta2 https://rubygems.org/gems/net-ssh/versions/6.0.0.beta2 

if you can try your app with that, and report back that would be awesome!

**Comment by dirkjonker** [comment]
Would love to do that, however we need `net-scp` which has a restriction on net-ssh to be `< 6.0.0`

**Comment by mfazekas** [comment]
@dirkjonker i'll try to look into net-scp later today

**Comment by mfazekas** [comment]
@dirkjonker sorry for the delay i've release net-scp 3.0.0.rc1 it should allow net-ssh 6.0.0

**Comment by dirkjonker** [comment]
@mfazekas great. Will test it asap and get back to you!

**Comment by dirkjonker** [comment]
@mfazekas we've been deploying using the net-ssh/net-scp releace candidates for over 2 weeks without any issues, thanks for the effort

**Pull request closed without merging**
