### PR TITLE
UTF-8 buffer building encoding fixes - backport of #407

### PR DESCRIPTION
**Pull request by Iristyle**
This is a follow-on to backport #407 to the 3.x release branch.  This follows on from the discussion in #394 / #395 / #396 / #397

### CODE REVIEW

**Comment by Iristyle** [comment]
The results of `bundle exec rake test` under Ruby 2.3.1:


```
/Users/Iristyle/source/net-ssh/test/connection/test_channel.rb:434: warning: shadowing outer local variable - t
/Users/Iristyle/source/net-ssh/test/connection/test_channel.rb:434: warning: shadowing outer local variable - p
/Users/Iristyle/source/net-ssh/test/connection/test_channel.rb:439: warning: mismatched indentations at 'end' with 'def' at 430
/Users/Iristyle/source/net-ssh/lib/net/ssh/connection/session.rb:466: warning: mismatched indentations at 'end' with 'if' at 463
/Users/Iristyle/source/net-ssh/test/transport/kex/test_ecdh_sha2_nistp384.rb:38: warning: mismatched indentations at 'end' with 'unless' at 3
Loaded suite /Users/Iristyle/source/net-ssh/.bundle/gems/ruby/2.3.0/gems/rake-11.2.2/lib/rake/rake_test_loader
Started
..................................................................................................................
..................................................................................................................
..................................................................................................................
..................................................................................................................
..................................................................................................................
..................................................................................................................
..................................................................................................................
..................................................................................................................
..................................................................................................................
..................................................................................................................
..................................................................................................................
..................................................................................................................
..................................................................................................................
..................................................................................................................
..................................................................................................................
..................................................................................................................
..................................................................................................................
................................................

Finished in 1.453318 seconds.
------------------------------------------------------------------------------------------------------------------
1986 tests, 6271 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
------------------------------------------------------------------------------------------------------------------
1366.53 tests/s, 4314.95 assertions/s
```

**Comment by mfazekas** [comment]
What is the reason you need it at 3.1? I have really limited time and i'd much rather spend those resources on 4.0 than on 3.x.

**Comment by Iristyle** [comment]
Well, for one thing - there is no stable 4.0 release yet. Everything is
marked as alpha or beta.

Also, since there is a semver bump from 3 to 4, that requires vetting any
breaking changes that may impact Beaker. It's a lot easier for us to take a
minor patch in the 3.x series.

Thanks!

**Comment by Iristyle** [comment]
@mfazekas any thoughts about merging this into the 3.x series and cutting an updated gem with this Unicode fix?

Thanks!

**Comment by mfazekas** [comment]
@Iristyle i've release 3.3.0.beta1
https://rubygems.org/gems/net-ssh/versions/3.3.0.beta1
For lack of time there will be no final release, further updates to 3.* or 2.* releases.

**Pull request merged**
